### PR TITLE
Yuki sulpher

### PR DESCRIPTION
**Pull request by yuki-nmi**
Some B_LG_CBS x B_B_AK combinatoins miss 'clust' values (which determines 'benodigde S uit grond en bemesting (‘slv_av’)'. This results NA values for I_C_S. Clust numbers need to be assigned to all combinations.

### CODE REVIEW

**Comment by SvenVw** [comment]
Combinations of soil type and region that do not exists in table 6.2 of Handboek Bodem & Bemesting are now solved by using the average value of the soil type and ignoring the region

**Comment by SvenVw** [comment]
The evaluation of I_C_S for arable should not be changed. An `sbal` of larger than 0 should always give an ind of 1, because no fertilization is needed anymore as the soil delivers enough S for that crop

**Comment by SvenVw** [comment]
@yuki-nmi shall we merge this PR?

**Comment by yuki-nmi** [comment]
I am still doubting to use the abrupt shift of I_C_S from 0 to 1 for arable land. Theoretically it's true that S availability is enough whtn sbal > 0. However, sbal is derived from a continuous variable SLV and several other constants from lookup table, and a slight change in SLV can results in either I_C_S =1 or I_C_S = 0. This sounds like an artifact.

**Comment by SvenVw** [comment]
I changed the evaluation funtion to a logistic one to get a more smooth transition

**Pull request merged**
